#!/bin/bash 

awk -F ":" '{ print $1,$3,$7}' /etc/passwd | tail -n 72
#awk -F ":" '{ print "\x1B[32mlogin\x1B[0m [ \x1B[32m"$1 "\x1B[0m ], \x1B[34mUID\x1B[0m [ \x1B[34m"$3"\x1B[0m ], \x1b[31mpath\x1B[0m [ \x1B[31m" $7"\x1B[0m ]"}' /etc/passwd | tail -n 72

